const axios = require('axios');

const API_KEYS = [
    'Koja-64118e456c1d20ec4b75a9914ec70f6a',
    'Koja-3ce2fd6170ea41e13acf3e7e347a5719',
    'Koja-096a3b8e8046783b1b59643a548ae35d',
    'Koja-3b4890c331f417fa032e5cb742536388',
    'Koja-d9f9832a9b1807464b1c29aa85d33884',
    'Koja-bb2fc781169ad50d3280bf439172a791',
    'Koja-de9c2119108b41d707c5373d17743775',
    'Koja-9a6e21a46b350a2db52e6153f949c5d3',
    'Koja-ef5212fc41c708ef3f9ff64c59c64a15',
    'Koja-efa906b944d62eff99ac2865b99d852c',
    'Koja-16ce4852551ef858de2e5ae9892d7740',
    'Koja-f3d5f82f027dddb837f6a3af343eb732',
    'Koja-a66bb0884f9877fd0fffec8774d40c05'
];

const BASE_URL = 'https://kojaxd-api.vercel.app/ai/sunoai';

function getRandomApiKey() {
    return API_KEYS[Math.floor(Math.random() * API_KEYS.length)];
}

async function createTask(prompt, style, title) {
    const apiKey = getRandomApiKey();
    const url = `${BASE_URL}?apikey=${apiKey}&action=create&prompt=${encodeURIComponent(prompt)}&style=${encodeURIComponent(style)}&title=${encodeURIComponent(title)}`;
    const response = await axios.get(url);
    if (response.data.status) {
        return response.data.task_id;
    }
    throw new Error(response.data.message || 'Failed to create task');
}

async function checkTaskStatus(taskId) {
    const apiKey = getRandomApiKey();
    const url = `${BASE_URL}?apikey=${apiKey}&action=status&task_id=${taskId}`;
    const response = await axios.get(url);
    if (response.data.status) {
        return response.data.result;
    }
    throw new Error(response.data.message || 'Failed to get task status');
}

async function sunoCommand(sock, chatId, message) {
    try {
        const text = message.message?.conversation || message.message?.extendedTextMessage?.text;
        if (!text) return;

        const parts = text.split(' ');
        const query = parts.slice(1).join(' ').trim();

        if (!query) {
            return await sock.sendMessage(chatId, {
                text: "❌ Please provide a song prompt.\n\nUsage: .suno song prompt"
            }, { quoted: message });
        }

        await sock.sendMessage(chatId, { react: { text: '🎵', key: message.key } });

        // Set default values or extract from query if possible
        const prompt = query;
        const style = 'Pop'; // Default style
        const title = 'Raza AI Song'; // Default title

        const taskId = await createTask(prompt, style, title);
        
        let audioUrl = null;
        let attempts = 0;
        const maxAttempts = 20; // Max 200 seconds (20 * 10s)

        while (!audioUrl && attempts < maxAttempts) {
            attempts++;
            const result = await checkTaskStatus(taskId);
            
            if (result && result.length > 0 && result[0].data?.data?.length > 0) {
                audioUrl = result[0].data.data[0].audioUrl;
                const imageUrl = result[0].data.data[0].imageUrl;
                const songTitle = result[0].data.data[0].title || title;

                if (audioUrl) {
                    await sock.sendMessage(chatId, {
                        audio: { url: audioUrl },
                        mimetype: 'audio/mp4',
                        ptt: false,
                        contextInfo: {
                            externalAdReply: {
                                title: songTitle,
                                body: 'Generated by Suno AI',
                                mediaType: 1,
                                sourceUrl: '',
                                thumbnail: imageUrl ? await (await axios.get(imageUrl, { responseType: 'arraybuffer' })).data : null,
                                renderLargerThumbnail: true
                            }
                        }
                    }, { quoted: message });
                    return;
                }
            }

            await new Promise(resolve => setTimeout(resolve, 10000));
        }

        if (!audioUrl) {
            throw new Error('Generation timed out or failed.');
        }

    } catch (error) {
        console.error('Suno Command Error:', error);
        await sock.sendMessage(chatId, {
            text: `❌ Error: ${error.message}`
        }, { quoted: message });
    }
}

module.exports = sunoCommand;
